# Generated by Django 2.0 on 2018-05-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photography',
        ),
    ]
