# Generated by Django 2.0 on 2018-05-08 09:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_photography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='video_tut',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
