# Generated by Django 2.0 on 2018-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180508_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='video_tut',
            field=models.TextField(),
        ),
    ]
