# Generated by Django 2.0 on 2018-05-08 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180508_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_tut_name',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
