# Generated by Django 2.0 on 2018-05-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180508_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotutorial',
            old_name='video_tut',
            new_name='video_link',
        ),
    ]
