# Generated by Django 2.0 on 2018-05-10 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180508_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='written_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
