# Generated by Django 2.0 on 2018-05-10 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180510_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='written_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
