# Generated by Django 2.0 on 2018-05-11 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180510_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='Chords',
            new_name='chords',
        ),
        migrations.AlterField(
            model_name='guitar',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
