# Generated by Django 2.0 on 2018-05-11 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180511_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtutorial',
            name='blog_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
