# Generated by Django 2.0 on 2018-05-12 06:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
