# Generated by Django 2.0 on 2018-05-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='upload',
        ),
    ]
